#!/bin/bash

set -eu
trap exit INT TERM

################################################################################

TARGET_PACKAGE=""
while [ $# -gt 0 ] ; do
key="$1"
case $key in
  --pkg)  TARGET_PACKAGE="$2";  shift; shift; ;;
  *)                            shift;        ;;
esac
done

################################################################################

if [ -z "${TARGET_PACKAGE}" ] ; then
  (>&2 echo "[error] target package not provided")
  exit 1
fi

################################################################################

lifecycle::scala::lint() {
  local dir="$1"
  if [ -z ${dir} -o ! -d ${dir} ] ; then
    return
  fi
  cd ${dir} && sbt -Dsbt.ivy.home=${dir}/.ivy scalafmtAll
}

################################################################################

lifecycle::scala::lint \
  /project/services/${TARGET_PACKAGE}
