#!/bin/bash

set -eu
trap exit INT TERM

################################################################################

ARCH="amd64"
PLATFORM="linux"
SOURCE=""
OUTPUT=""
while [ $# -gt 0 ] ; do
key="$1"
case $key in
  --arch)   ARCH=${2#*/}; PLATFORM=${2%%/*}; shift; shift; ;;
  --source) SOURCE="$2";                     shift; shift; ;;
  --output) OUTPUT="$2";                     shift; shift; ;;
  *)                                         shift;        ;;
esac
done

################################################################################

if [ -z "${SOURCE}" ] ; then
  (>&2 echo "[error] source package not provided")
  exit 1
fi

if [ -z "${OUTPUT}" ] ; then
  (>&2 echo "[error] output not provided")
  exit 1
fi

OUTPUT_FILE=${OUTPUT}/$(basename ${SOURCE})-${PLATFORM}-${ARCH}

################################################################################

lifecycle::scala::pack() {
  local source="$1"
  if [ -z ${source} -o ! -d ${source} ] ; then
    return
  fi

  local output="$2"
  if [ -z ${output} ] ; then
    return
  fi

  if [ -d ${output} ] ; then
    rm -rf ${output}
  fi

  cd ${source} && sbt \
    -Dsbt.coursier.home="${source}/.coursier" \
    pack

  mkdir -p ${output}

  cp -R ${source}/target/pack/bin ${output}
  cp -R ${source}/target/pack/lib ${output}

  echo "[info] ${output} packed"
}

################################################################################

lifecycle::scala::pack \
  ${SOURCE} \
  ${OUTPUT_FILE}

du -hs ${OUTPUT_FILE}
