#!/bin/bash

set -eu
trap exit INT TERM

################################################################################

TARGET_PACKAGE=""
while [ $# -gt 0 ] ; do
key="$1"
case $key in
  --pkg)  TARGET_PACKAGE="$2";  shift; shift; ;;
  *)                            shift;        ;;
esac
done

################################################################################

if [ -z "${TARGET_PACKAGE}" ] ; then
  (>&2 echo "[error] target package not provided")
  exit 1
fi

################################################################################

lifecycle::scala::sec() {
  local dir="$1"
  if [ -z ${dir} -o ! -d ${dir} ] ; then
    return
  fi
  #gosec -exclude=G104,G302 "${dir}/..."
  echo "nothing to sec at ${dir}"
}

################################################################################

lifecycle::scala::sec \
  /project/services/${TARGET_PACKAGE}
