#!/bin/bash

set -eu
trap exit INT TERM

################################################################################

SOURCE=""
while [ $# -gt 0 ] ; do
key="$1"
case $key in
  --source)  SOURCE="$2";  shift; shift; ;;
  *)                       shift;        ;;
esac
done

################################################################################

if [ -z "${SOURCE}" ] ; then
  (>&2 echo "[error] source package not provided")
  exit 1
fi

################################################################################

lifecycle::scala::sync() {
  local dir="$1"
  if [ -z ${dir} -o ! -d ${dir} ] ; then
    return
  fi

  if [ -d ${dir}/vendor ] ; then
    rm -rf ${dir}/vendor
  fi

  if [ -f ${dir}/go.sum ] ; then
    rm -f ${dir}/go.sum
  fi

  cd ${dir} && sbt -Dsbt.ivy.home=${dir}/.ivy clean
  cd ${dir} && sbt -Dsbt.ivy.home=${dir}/.ivy update
  cd ${dir} && sbt -Dsbt.ivy.home=${dir}/.ivy evicted
}

################################################################################

lifecycle::scala::sync \
  ${SOURCE}
