#!/bin/bash

set -e
trap exit INT TERM

TARGET_PACKAGE=""
OUTPUT=""

while [ $# -gt 0 ] ; do
key="$1"

case $key in

  --pkg)
    TARGET_PACKAGE="$2"
    shift
    shift
  ;;

  --output)
    OUTPUT="$2"
    shift
    shift
  ;;

  *)
    shift
  ;;

esac
done

if [ -z "${TARGET_PACKAGE}" ] ; then
  (>&2 echo "[error] target package not provided")
  exit 1
fi

if [ -z "${OUTPUT}" ] ; then
  (>&2 echo "[error] output not provided")
  exit 1
fi

cd /project/services/${TARGET_PACKAGE}

echo "test NOT IMPLEMENTED"
