version: '2.1'

# ---------------------------------------------------------------------------- #

services:

  # -------------------------------------------------------------------------- #

  scala: &scala
    image: jancajthaml/scala:amd64
    volumes:
      - .:/project
    working_dir: /project
    tty: true

  # -------------------------------------------------------------------------- #

  debian: &debian
    image: jancajthaml/debian-packager
    volumes:
      - .:/project
    working_dir: /project
    tty: true

  # -------------------------------------------------------------------------- #

  sync:
    <<: *scala
    entrypoint: ["/project/dev/lifecycle/sync"]

  # -------------------------------------------------------------------------- #

  update:
    <<: *scala
    entrypoint: ["/project/dev/lifecycle/update"]

  # -------------------------------------------------------------------------- #

  lint:
    <<: *scala
    entrypoint: ["/project/dev/lifecycle/lint"]

  # -------------------------------------------------------------------------- #

  sec:
    <<: *scala
    entrypoint: ["/project/dev/lifecycle/sec"]

  # -------------------------------------------------------------------------- #

  package:
    <<: *scala
    entrypoint: ["/project/dev/lifecycle/package"]

  # -------------------------------------------------------------------------- #

  release:
    <<: *scala
    entrypoint: ["/project/dev/lifecycle/release"]

  # -------------------------------------------------------------------------- #

  debian-package:
    <<: *debian
    entrypoint: ["/project/dev/lifecycle/debian"]

  # -------------------------------------------------------------------------- #

  test:
    <<: *scala
    entrypoint: ["/project/dev/lifecycle/test"]

  # -------------------------------------------------------------------------- #

  artifacts:
    build:
      dockerfile: Dockerfile
      context: .
    image: openbank/data-warehouse

  # -------------------------------------------------------------------------- #

  postgres:
    hostname: postgres
    build:
      dockerfile: Dockerfile
      context: bbtest/postgres

  # -------------------------------------------------------------------------- #

  bbtest:
    image: jancajthaml/bbtest:amd64
    environment:
      IMAGE_VERSION: ${VERSION:-latest}-${META:-master}
      UNIT_VERSION: ${VERSION:-latest}
      UNIT_ARCH: amd64
    depends_on:
      - postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/lib/docker/containers:/var/lib/docker/containers:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./bbtest:/opt/app
      - ./reports:/tmp/reports
    working_dir: /opt/app

# ---------------------------------------------------------------------------- #
