version: '3.7'

# ---------------------------------------------------------------------------- #

services:

  # -------------------------------------------------------------------------- #

  scala: &scala
    image: jancajthaml/scala:${ARCH}
    tty: true
    volumes:
      - .:/project:delegated
    working_dir: /project

  # -------------------------------------------------------------------------- #

  debian: &debian
    image: jancajthaml/debian-packager
    tty: true
    volumes:
      - .:/project:delegated
    working_dir: /project

  # -------------------------------------------------------------------------- #

  sync:
    <<: *scala
    entrypoint:
      - /project/dev/lifecycle/sync

  # -------------------------------------------------------------------------- #

  lint:
    <<: *scala
    entrypoint:
      - /project/dev/lifecycle/lint

  # -------------------------------------------------------------------------- #

  sec:
    <<: *scala
    entrypoint:
      - /project/dev/lifecycle/sec

  # -------------------------------------------------------------------------- #

  package:
    <<: *scala
    entrypoint:
      - /project/dev/lifecycle/package

  # -------------------------------------------------------------------------- #

  release:
    <<: *debian
    entrypoint:
      - /project/dev/lifecycle/release

  # -------------------------------------------------------------------------- #

  debian-package:
    <<: *debian
    entrypoint:
      - /project/dev/lifecycle/debian

  # -------------------------------------------------------------------------- #

  test:
    <<: *scala
    entrypoint:
      - /project/dev/lifecycle/test

  # -------------------------------------------------------------------------- #

  bbtest:
    image: jancajthaml/bbtest:${ARCH}
    tty: true
    environment:
      VERSION: ${VERSION}
      META: ${META}
      CI: ${CI:-false}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /var/lib/docker/containers:/var/lib/docker/containers:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - .:/opt/app:delegated
    working_dir: /opt/app

# ---------------------------------------------------------------------------- #
