#!/bin/sh

set -e

case "$1" in

  install|upgrade)
    if [ ! -f "/etc/init/dwh.conf" ] ; then
      mkdir -p /etc/init
      touch /etc/init/dwh.conf

      echo "DWH_LOG_LEVEL=INFO" >> /etc/init/dwh.conf
      echo "DWH_HTTP_PORT=8443" >> /etc/init/dwh.conf
      echo "DWH_POSTGRES_URL=jdbc:postgresql://127.0.0.1:5432/openbank" >> /etc/init/dwh.conf
      echo "DWH_PRIMARY_STORAGE_PATH=/data" >> /etc/init/dwh.conf
    fi

  ;;

  abort-upgrade)
  ;;

  *)
    (>&2 echo "preinst called with unknown argument \`$1'")
    exit 1
  ;;

esac

exit 0
