#!/bin/sh

set -e

enable() {
  wanted_by=$(cat /lib/systemd/system/${1} | sed -n -e 's/^.*WantedBy=//p')
  mkdir -p /etc/systemd/system/${wanted_by}.wants
  ln -s \
    "/lib/systemd/system/${1}" \
    "/etc/systemd/system/${wanted_by}.wants/${1}"
}

case "$1" in

  configure)
    if [ -f /etc/init/data-warehouse.conf ] ; then
      enable data-warehouse.path
      enable data-warehouse.service
      enable data-warehouse-app.service
      (systemctl daemon-reload >/dev/null 2>&1 || :)
      (systemctl start data-warehouse.service >/dev/null 2>&1 || :)
      (systemctl start data-warehouse-app.service >/dev/null 2>&1 || :)
      (systemctl start data-warehouse.path >/dev/null 2>&1 || :)
    else
      (>&2 echo "/etc/init/data-warehouse.conf file not found")
      exit 1
    fi
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    (>&2 echo "postinst called with unknown argument \ `$1`")
    exit 1
  ;;

esac

exit 0
