#!/bin/sh

set -e

case "$1" in

  install|upgrade)
    if [ ! -f "/etc/init/dwh.conf" ] ; then
      mkdir -p /etc/init
      touch /etc/init/dwh.conf

      echo "DWH_LOG_LEVEL=INFO" >> /etc/init/dwh.conf
      echo "DWH_HTTP_PORT=8443" >> /etc/init/dwh.conf
      echo "DWH_POSTGRES_URL=jdbc:postgresql://127.0.0.1:5432/openbank" >> /etc/init/dwh.conf
      echo "DWH_PRIMARY_STORAGE_PATH=/data" >> /etc/init/dwh.conf
    fi

    secrets=$(sed -n -e 's/^.*DWH_SECRETS=//p' /etc/init/dwh.conf 2>/dev/null | awk '{gsub(/^ +| +$/,"")} {print $0}')

    if [ -z "${secrets}" ] ; then
      (>&2 echo "REPORTING_SECRETS are not defined at /etc/init/dwh.conf")
      exit 1
    fi

    if [ ! -f "${secrets}/domain.local.crt" ] || [ ! -f "${secrets}/domain.local.key" ] ; then
      mkdir -p "${secrets}"

      openssl req \
        -x509 \
        -nodes \
        -newkey rsa:2048 \
        -keyout "${secrets}/domain.local.key" \
        -out "${secrets}/domain.local.crt" \
        -days 1 \
        -subj "/C=CZ/ST=Czechia/L=Prague/O=OpenBanking/OU=IT/CN=localhost/emailAddress=jan.cajthaml@gmail.com"
      echo "generated temporary certificates at ${secrets} valid for 24 hours"
    fi

  ;;

  abort-upgrade)
  ;;

  *)
    (>&2 echo "preinst called with unknown argument \`$1'")
    exit 1
  ;;

esac

exit 0
