.nh
.TH "DATA-WAREHOUSE" "1" "Jul 2020" "Data Warehouse" "OpenBank Data Warehouse Server Manual"
.sp
.SH "NAME"
data-warehouse \- starts openbank data warehouse GraphQL server
.SH "SYNOPSIS"
.sp
.nf
\fIdata-warehouse
.fi
.sp
.SH "DESCRIPTION"
.sp
The data warehouse provides secondary data mirror for analytics
.sp
.SH "AUTHORS"
.sp
Jan Cajthaml <jan.cajthaml@gmail.com>
.sp
