name: Health Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '*/30 * * * *'

jobs:

  build:
    name: From Scratch Test
    runs-on: ubuntu-latest
    steps:

    - name: Prepare
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk
        architecture: x64
      id: scala

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install static dependencies
      run: |
        cd services/data-warehouse

        sbt -Dsbt.ivy.home=.ivy clean
        sbt -Dsbt.ivy.home=.ivy update
        sbt -Dsbt.ivy.home=.ivy evicted

    - name: Unit Test
      run:  |
        cd services/data-warehouse

        sbt -Dsbt.ivy.home=.ivy test
